### ISSUE TITLE
Associations

### ISSUE THREAD

**Issue by tabishiqbal** [kuroda/vue-form-for#1]
Hey! Awesome Gem.

How would you handle associations?

**Comment by matissg** [comment]
Hi! Looks like I could try the gem in my project. I'm thinking, how to create nested form with it? Any example code would be nice. Thank you.

**Comment by kuroda** [comment]
@matissg Unfortunately, this gem cannot handle association, for now at least.

I was and am busy for a while. I'm sorry.

**Comment by kuroda** [comment]
The version 0.7.0 supports the nested attributes.

Please see https://github.com/kuroda/vue-rails-form-builder-demo
