### ISSUE TITLE
Question: how to use v-for for dynamic attributes?

### ISSUE THREAD

**Issue by dceluis** [kuroda/vue-form-for#2]
Hi! Thank you for such a helpful gem.

Is there any way to create nested attributes with v-for? Right now, I tried use fields_for, but if the model has more than one association record then you get more than one element with a v-for.

I attach a screenshot so it's more clear: 
![image](https://user-images.githubusercontent.com/5464881/34633132-0422531c-f248-11e7-8b83-99e002516ee1.png)

**Comment by kuroda** [comment]
@sanchez2210 Thank you for the feedback.

I think your problem can be solved like this:

    <div class="form-group>
      <%= f.fields_for :milestone, @roadmap.milestones do |g| %>
        <%= g.hidden_field :title %>
      <% end %>
      <input type="text"
        v-for="(m, index) in roadmap.milestones_attributes"
        v-model="roadmap.milestones_attributes[index].title"
        :name="'roadmap[milestones_attributes][' + index + '][title]'">
    </div>

Sorry if misunderstand what you want to achieve.

**Comment by dceluis** [comment]
Thank you for the reply! @kuroda 
Unfortunately, that's not going to work, since I'm also using vue-data-scooper, and the plugin builds the data attribute from the `v-model` attributes AFAIK.

So my data object ends up looking like this: 
![image](https://user-images.githubusercontent.com/5464881/34640407-19a641f8-f2c0-11e7-92a0-fa660cf51fa6.png)

Do you think vue-data-scooper should build the data from the `name` attributes instead? 

Cheers!

**Comment by kuroda** [comment]
@sanchez2210 

In my environment, my idea seems to go well.

I have constructed a demo: https://github.com/kuroda/vue-rails-form-builder-demo

Clone this demo and checkout the branch `fields_for_experimental`.

After starting the Rails server and webpack dev server, go to the Database Scaffold Form, add a new customer and edit it.

You will see three text inputs for the phone numbers:

![v-for-1](https://user-images.githubusercontent.com/5565/34640974-1d3e8f3e-f340-11e7-8ecf-8e74efe1995f.png)

Here is the data of `phones_attributes`:

![v-for-0](https://user-images.githubusercontent.com/5565/34640975-1df7bdce-f340-11e7-9a96-fd580e7d8db8.png)

Compare carefully its [app/views/customers/_fields.html.erb](https://github.com/kuroda/vue-rails-form-builder-demo/blob/fields_for_experimental/app/views/customers/_fields.html.erb#L25-L36) with your code.

I believe that you made some mistakes on your HTML template. Please share it if possible.

**Comment by kuroda** [comment]
I close this issue because no discussion occurs for a while. Please reopen it if necessary.
