### ISSUE TITLE
File input fields produce error

### ISSUE THREAD

**Issue by djchadderton** [kuroda/vue-form-for#3]
The builder works well for any fields apart from file input fields. I have a fields_for in my form for adding images, and my console error message looks like this:

`- <input v-model="review.images_attributes[6].image" type="file">:
File inputs are read only. Use a v-on:change listener instead.`

As the builder automatically adds the v-model, there's no opportunity to exclude the input forms and add a v-on:change instead as far as I can tell.

**Comment by kuroda** [comment]
@djchadderton Thank you for reporting issue.

This is a bug. I will fix it as soon as possible.
